swagger: '2.0'
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths:
  /api/v1/pokemon/{pokemonId}:
    post:
      tags:
        - collection
      summary: Add Pokémon to collection
      operationId: postAddPokemonToCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: The Pokémon's ID to add to the collection
        - name: caught
          in: body
          schema:
            $ref: '../definitions/collection.yml#/definitions/Collection'
      responses:
        "201":
          description: Pokémon added to collection successfully
        "400":
          description: Invalid input data (e.g., invalid date or nickname)
        "409":
          description: Pokémon is already in the collection
        "404":
          description: Pokémon or user not found
  /api/v1/collection/pokemon:
    get:
      tags:
        - collection
      summary: search Pokémon by attribute (name, type, etc.)
      operationId: searchPokemon
      parameters:
        - name: name
          in: query
          required: false
          type: string
          description: Pokémon name to search for
        - name: type
          in: query
          required: false
          type: string
          description: Pokémon type to search for
        - name: generation
          in: query
          required: false
          type: integer
          description: Pokémon generation to search for
        - name: legendary
          in: query
          required: false
          type: boolean
          description: Whether to search for legendary Pokémon
        - name: limit
          in: query
          required: false
          type: integer
          description: Number of Pokémon to return per page
          default: 10
        - name: offset
          in: query
          required: false
          type: integer
          description: Starting point for the collection
          default: 0
      responses:
        "200":
          description: Search results for Pokémon
          schema:
            type: array
            items:
              $ref: "../definitions/pokemon.yml#/definitions/Pokemon"
        "400":
          description: Invalid search parameters
  /api/v1/collection/pokemon/{pokemonId}:
    delete:
      tags:
        - collection
      summary: delete Pokémon from collection
      operationId: deletePokemonFromCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: Pokémon's ID to delete
      responses:
        "200":
          description: Pokémon removed from collection successfully
        "404":
          description: Pokémon or collection not found
    put:
      description: edit a Pokémon in user's collection
      tags:
        - collection
      summary: edit Pokémon details in collection
      operationId: putEditPokemonInCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: Pokémon's ID to edit
        - name: caught
          in: body
          required: true
          schema:
            $ref: '../definitions/collection.yml#/definitions/Collection'
      responses:
        "200":
          description: Pokémon updated in collection successfully
        "400":
          description: Invalid input data
        "404":
          description: Pokémon or collection not found
 