swagger: '2.0'
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths:
  /api/v1/pokemon/{pokemonId}:
    get:
      tags:
        - pokemon
      summary: retrieve details for a specific pokemon by id
      operationId: getPokemon
      produces:
        - application/json
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: id of pokemon
      responses:
        "200":
          description: GetPokemonResponse
          schema:
            $ref: "../definitions/pokemon.yml#/definitions/GetPokemonResponse"
        "400":
          description: invalid id 
        "404":
          description: pokemon not found
    post:
      security:
        - Bearer: []
      tags:
        - collection
      summary: add pokemon to collection
      operationId: postAddPokemonToCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: pokemon's ID to add to the collection
        - name: body
          in: body
          schema:
            $ref: '../definitions/collection.yml#/definitions/PokemonBody'
      responses:
        "201":
          description: pokemon added to collection successfully
        "400":
          description: invalid input data
        "409":
          description: pokemon is already in the collection
        "404":
          description: pokemon or user not found
  /api/v1/collection/pokemon:
    get:
      security:
        - Bearer: []
      tags:
        - collection
      summary: get all pokemon in collection or search pokemon by attribute (name, type, etc.)
      operationId: getCollectionPokemon
      parameters:
        - name: name
          in: query
          required: false
          type: string
          description: pokemon name to search for
        - name: type
          in: query
          required: false
          type: string
          description: pokemon type to search for
        - name: hp
          in: query
          required: false
          type: integer
          description: pokemon hp to search for
        - name: attack
          in: query
          required: false
          type: integer
          description: pokemon attack to search for
        - name: defense
          in: query
          required: false
          type: integer
          description: pokemon defense to search for
        - name: speed
          in: query
          required: false
          type: integer
          description: pokemon speed to search for
        - name: special
          in: query
          required: false
          type: integer
          description: pokemon special to search for
        - name: limit
          in: query
          required: false
          type: integer
          description: number of pokemon to return per page
          default: 10
          maximum: 20
        - name: offset
          in: query
          required: false
          type: integer
          description: number of pokemon to skip before returning results
          default: 0
          minimum: 0
        - name: sortOrder
          in: query
          required: false
          type: string
          enum: [asc, desc]
          description: order for the results ("asc" ascending, "desc" descending)
      responses:
          "200":
            description: GetCollectionPokemonResponse
            schema:
              $ref: "../definitions/collection.yml#/definitions/GetCollectionPokemonResponse"
          "400":
            description: invalid search parameters
  /api/v1/collection/pokemon/{pokemonId}:
    get:
      security:
        - Bearer: []
      tags:
        - collection
      summary: retrieve details for a pokemon from collection
      operationId: getCollectionPokemonDetail
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: pokemon ID to retrieve details for
      responses:
        "200":
          description: GetCollectionPokemonDetailResponse
          schema:
            $ref: "../definitions/collection.yml#/definitions/GetCollectionPokemonDetailResponse"
        "404":
          description: pokemon or collection not found
    delete:
      security:
        - Bearer: []
      tags:
        - collection
      summary: delete pokemon from collection
      operationId: deletePokemonFromCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: pokemon's ID to delete
      responses:
        "200":
          description: pokemon removed from collection successfully
        "404":
          description: pokemon or collection not found
    put:
      security:
        - Bearer: []
      description: edit a pokemon in user's collection
      tags:
        - collection
      summary: edit pokemon details in collection
      operationId: putEditPokemonInCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: pokemon id to edit
        - name: body
          in: body
          required: true
          description: nickname and caught date
          schema:
            $ref: '../definitions/collection.yml#/definitions/PokemonBody'
      responses:
        "200":
          description: pokemon updated in collection successfully
        "400":
          description: invalid input data
        "404":
          description: pokemon or collection not found


  