swagger: '2.0'
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths:
  /api/v1/pokemon/{pokemonId}:
    post:
      security:
        - Bearer: []
      tags:
        - collection
      summary: add pokemon to collection
      operationId: postAddPokemonToCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: pokemon's ID to add to the collection
        - name: caught
          in: body
          schema:
            $ref: '../definitions/collection.yml#/definitions/Collection'
      responses:
        "201":
          description: pokemon added to collection successfully
        "400":
          description: invalid input data (e.g., invalid date or nickname)
        "409":
          description: pokemon is already in the collection
        "404":
          description: pokemon or user not found
  /api/v1/collection/pokemon:
    get:
      security:
        - Bearer: []
      tags:
        - collection
      summary: search pokemon by attribute (name, type, etc.)
      operationId: searchPokemon
      parameters:
        - name: name
          in: query
          required: false
          type: string
          description: pokemon name to search for
        - name: type
          in: query
          required: false
          type: string
          description: pokemon type to search for
        - name: generation
          in: query
          required: false
          type: integer
          description: pokemon generation to search for
        - name: legendary
          in: query
          required: false
          type: boolean
          description: whether to search for legendary pokemon
        - name: limit
          in: query
          required: false
          type: integer
          description: number of pokemon to return per page
          default: 10
          maximum: 20
        - name: offset
          in: query
          required: false
          type: integer
          description: number of pokemon to skip before returning results
          default: 0
          minimum: 0
      responses:
        "200":
          description: search results for pokemon
          schema:
            type: array
            items:
              $ref: "../definitions/pokemon.yml#/definitions/Pokemon"
        "400":
          description: invalid search parameters
  /api/v1/collection/pokemon/{pokemonId}:
    delete:
      security:
        - Bearer: []
      tags:
        - collection
      summary: delete pokemon from collection
      operationId: deletePokemonFromCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: pokemon's ID to delete
      responses:
        "200":
          description: pokemon removed from collection successfully
        "404":
          description: pokemon or collection not found
    put:
      security:
        - Bearer: []
      description: edit a pokemon in user's collection
      tags:
        - collection
      summary: edit pokemon details in collection
      operationId: putEditPokemonInCollection
      parameters:
        - name: pokemonId
          in: path
          required: true
          type: string
          description: pokemon's ID to edit
        - name: caught
          in: body
          required: true
          schema:
            $ref: '../definitions/collection.yml#/definitions/Collection'
      responses:
        "200":
          description: pokemon updated in collection successfully
        "400":
          description: invalid input data
        "404":
          description: pokemon or collection not found
 