swagger: '2.0'
info:
   title: github.com/ansiegl/Pok-Nest.git
   version: 0.1.0
paths:
  /api/v1/pokemon:
      get:
        tags:
          - pokemon
        summary: retrieve all pokemon data as JSON or search pokemon by attribute (name, type, etc.)
        operationId: getPokemonAsJson
        produces:
          - application/json
        parameters:
          - name: name
            in: query
            required: false
            type: string
            description: name of pokemon
          - name: type
            in: query
            required: false
            type: string
            description: pokemon type to search for
          - name: hp
            in: query
            required: false
            type: integer
            description: pokemon hp to search for
          - name: attack
            in: query
            required: false
            type: integer
            description: pokemon attack to search for
          - name: defense
            in: query
            required: false
            type: integer
            description: pokemon defense to search for
          - name: speed
            in: query
            required: false
            type: integer
            description: pokemon speed to search for
          - name: special
            in: query
            required: false
            type: integer
            description: pokemon special to search for
          - name: limit
            in: query
            required: false
            type: integer
            description: number of pokemon to return per page
            default: 10
            maximum: 20
          - name: offset
            in: query
            required: false
            type: integer
            description: number of pokemon to skip before returning results
            default: 0
            minimum: 0
          - name: sortOrder
            in: query
            required: false
            type: string
            enum: [asc, desc]
            description: order for the results ("asc" ascending, "desc" descending)
        responses:
          "200":
            description: GetPokemonResponse
            schema:
              $ref: "../definitions/pokemon.yml#/definitions/GetPokemonResponse"
          "400":
            description: invalid query parameters
          "404":
            description: pokemon not found
  /api/v1/pokemon/download:
    get:
      tags:
        - pokemon
      summary: download all pokemon data as a CSV file
      operationId: downloadPokemonCSV
      produces:
        - text/csv
      responses:
        "200":
          description: Successful download of pokemon data
          schema:
            $ref: "../definitions/pokemon.yml#/definitions/GetDownloadResponse"
          headers:
            Content-Disposition:
              type: string
              description: 'attachment; filename=pokemon.csv'
        "500":
          description: internal server error