swagger: '2.0'
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths:
  /api/v1/pokemon/csv:
    get:
      tags:
        - pokemon
      summary: Retrieve a list of all Pokémon as CSV/JSON
      operationId: GetPokemonAsJson
      responses:
        "200":
          description: all Pokémon data
          schema:
            type: array
            items:
              $ref: "../definitions/pokemon.yml#/definitions/Pokemon"
