swagger: '2.0'
info:
   title: github.com/ansiegl/Pok-Nest.git
   version: 0.1.0
paths:
  /api/v1/pokemon:
    get:
      tags:
        - pokemon
      summary: get all pokemon
      operationId: getAllPokemon
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
          description: number of pokemon to return per page
          default: 10
          maximum: 20
        - name: offset
          in: query
          required: false
          type: integer
          description: number of pokemon to skip before returning results
          default: 0
          minimum: 0
      responses:
        "200":
          description: list of pokemon
          schema:
            $ref: "../definitions/pokemon.yml#/definitions/GetPokemonResponse"
        "400":
          description: invalid parameters
    post:
      tags:
        - pokemon
      summary: search for pokemon in collection by filter
      operationId: searchPokemon
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: "../definitions/pokemon.yml#/definitions/PokemonSearchRequest"
      responses:
        "200":
          description: list of pokemon matching search
          schema:
            $ref: "../definitions/pokemon.yml#/definitions/GetPokemonResponse"
        "400":
          description: invalid search parameters
  /api/v1/pokemon/download:
    get:
      tags:
        - pokemon
      summary: download all pokemon data as a CSV file
      operationId: downloadPokemonCSV
      produces:
        - text/csv
      responses:
        "200":
          description: Successful download of pokemon data
          schema:
            $ref: "../definitions/pokemon.yml#/definitions/GetDownloadResponse"
          headers:
            Content-Disposition:
              type: string
              description: 'attachment; filename=pokemon.csv'
        "500":
          description: internal server error