swagger: '2.0'
 info:
   title: github.com/ansiegl/Pok-Nest.git
   version: 0.1.0
 paths:
  /api/v1/pokemon:
    get:
      tags:
        - pokemon
      summary: retrieve all Pokémon data as CSV/JSON
      operationId: getPokemonAsJson
      produces:
        - application/json
        - text/csv
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
          description: The number of Pokémon to return per page (default is 10)
          default: 10
        - name: offset
          in: query
          required: false
          type: integer
          description: The starting point (page offset) for the collection (default is 0)
          default: 0
      responses:
        "200":
          description: paginated Pokémon data in CSV/JSON format
          schema:
            type: array
            items:
              $ref: "../definitions/pokemon.yml#/definitions/Pokemon"
        "400":
          description: invalid pagination parameters
