// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCollectionPokemons(t *testing.T) {
	t.Parallel()

	query := CollectionPokemons()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCollectionPokemonsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCollectionPokemonsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CollectionPokemons().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCollectionPokemonsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CollectionPokemonSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCollectionPokemonsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CollectionPokemonExists(ctx, tx, o.PokemonID, o.UserID)
	if err != nil {
		t.Errorf("Unable to check if CollectionPokemon exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CollectionPokemonExists to return true, but got false.")
	}
}

func testCollectionPokemonsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	collectionPokemonFound, err := FindCollectionPokemon(ctx, tx, o.PokemonID, o.UserID)
	if err != nil {
		t.Error(err)
	}

	if collectionPokemonFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCollectionPokemonsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CollectionPokemons().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCollectionPokemonsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CollectionPokemons().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCollectionPokemonsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	collectionPokemonOne := &CollectionPokemon{}
	collectionPokemonTwo := &CollectionPokemon{}
	if err = randomize.Struct(seed, collectionPokemonOne, collectionPokemonDBTypes, false, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}
	if err = randomize.Struct(seed, collectionPokemonTwo, collectionPokemonDBTypes, false, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = collectionPokemonOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = collectionPokemonTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CollectionPokemons().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCollectionPokemonsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	collectionPokemonOne := &CollectionPokemon{}
	collectionPokemonTwo := &CollectionPokemon{}
	if err = randomize.Struct(seed, collectionPokemonOne, collectionPokemonDBTypes, false, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}
	if err = randomize.Struct(seed, collectionPokemonTwo, collectionPokemonDBTypes, false, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = collectionPokemonOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = collectionPokemonTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testCollectionPokemonsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCollectionPokemonsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(collectionPokemonColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCollectionPokemonToOnePokemonUsingPokemon(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local CollectionPokemon
	var foreign Pokemon

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, collectionPokemonDBTypes, false, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, pokemonDBTypes, false, pokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pokemon struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.PokemonID = foreign.PokemonID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Pokemon().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.PokemonID != foreign.PokemonID {
		t.Errorf("want: %v, got %v", foreign.PokemonID, check.PokemonID)
	}

	slice := CollectionPokemonSlice{&local}
	if err = local.L.LoadPokemon(ctx, tx, false, (*[]*CollectionPokemon)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Pokemon == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Pokemon = nil
	if err = local.L.LoadPokemon(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Pokemon == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testCollectionPokemonToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local CollectionPokemon
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, collectionPokemonDBTypes, false, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := CollectionPokemonSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*CollectionPokemon)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testCollectionPokemonToOneSetOpPokemonUsingPokemon(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CollectionPokemon
	var b, c Pokemon

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, collectionPokemonDBTypes, false, strmangle.SetComplement(collectionPokemonPrimaryKeyColumns, collectionPokemonColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pokemonDBTypes, false, strmangle.SetComplement(pokemonPrimaryKeyColumns, pokemonColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, pokemonDBTypes, false, strmangle.SetComplement(pokemonPrimaryKeyColumns, pokemonColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Pokemon{&b, &c} {
		err = a.SetPokemon(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Pokemon != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.CollectionPokemons[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PokemonID != x.PokemonID {
			t.Error("foreign key was wrong value", a.PokemonID)
		}

		if exists, err := CollectionPokemonExists(ctx, tx, a.PokemonID, a.UserID); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}
func testCollectionPokemonToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CollectionPokemon
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, collectionPokemonDBTypes, false, strmangle.SetComplement(collectionPokemonPrimaryKeyColumns, collectionPokemonColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.CollectionPokemons[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		if exists, err := CollectionPokemonExists(ctx, tx, a.PokemonID, a.UserID); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testCollectionPokemonsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCollectionPokemonsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CollectionPokemonSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCollectionPokemonsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CollectionPokemons().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	collectionPokemonDBTypes = map[string]string{`PokemonID`: `uuid`, `UserID`: `uuid`, `Caught`: `date`, `Nickname`: `text`}
	_                        = bytes.MinRead
)

func testCollectionPokemonsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(collectionPokemonPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(collectionPokemonAllColumns) == len(collectionPokemonPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCollectionPokemonsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(collectionPokemonAllColumns) == len(collectionPokemonPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CollectionPokemon{}
	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, collectionPokemonDBTypes, true, collectionPokemonPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(collectionPokemonAllColumns, collectionPokemonPrimaryKeyColumns) {
		fields = collectionPokemonAllColumns
	} else {
		fields = strmangle.SetComplement(
			collectionPokemonAllColumns,
			collectionPokemonPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CollectionPokemonSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCollectionPokemonsUpsert(t *testing.T) {
	t.Parallel()

	if len(collectionPokemonAllColumns) == len(collectionPokemonPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CollectionPokemon{}
	if err = randomize.Struct(seed, &o, collectionPokemonDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CollectionPokemon: %s", err)
	}

	count, err := CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, collectionPokemonDBTypes, false, collectionPokemonPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CollectionPokemon struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CollectionPokemon: %s", err)
	}

	count, err = CollectionPokemons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
