// Code generated by go-swagger; DO NOT EDIT.

package collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetCollectionPokemonParams creates a new GetCollectionPokemonParams object
// with the default values initialized.
func NewGetCollectionPokemonParams() GetCollectionPokemonParams {

	var (
		// initialize parameters with default values

		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	return GetCollectionPokemonParams{
		Limit: &limitDefault,

		Offset: &offsetDefault,
	}
}

// GetCollectionPokemonParams contains all the bound params for the get collection pokemon operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCollectionPokemon
type GetCollectionPokemonParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*pokemon attack to search for
	  In: query
	*/
	Attack *int64 `query:"attack"`
	/*pokemon defense to search for
	  In: query
	*/
	Defense *int64 `query:"defense"`
	/*pokemon hp to search for
	  In: query
	*/
	Hp *int64 `query:"hp"`
	/*number of pokemon to return per page
	  Maximum: 20
	  In: query
	  Default: 10
	*/
	Limit *int64 `query:"limit"`
	/*pokemon name to search for
	  In: query
	*/
	Name *string `query:"name"`
	/*number of pokemon to skip before returning results
	  Minimum: 0
	  In: query
	  Default: 0
	*/
	Offset *int64 `query:"offset"`
	/*order for the results ("asc" ascending, "desc" descending)
	  In: query
	*/
	SortOrder *string `query:"sortOrder"`
	/*pokemon special to search for
	  In: query
	*/
	Special *int64 `query:"special"`
	/*pokemon speed to search for
	  In: query
	*/
	Speed *int64 `query:"speed"`
	/*pokemon type to search for
	  In: query
	*/
	Type *string `query:"type"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCollectionPokemonParams() beforehand.
func (o *GetCollectionPokemonParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAttack, qhkAttack, _ := qs.GetOK("attack")
	if err := o.bindAttack(qAttack, qhkAttack, route.Formats); err != nil {
		res = append(res, err)
	}

	qDefense, qhkDefense, _ := qs.GetOK("defense")
	if err := o.bindDefense(qDefense, qhkDefense, route.Formats); err != nil {
		res = append(res, err)
	}

	qHp, qhkHp, _ := qs.GetOK("hp")
	if err := o.bindHp(qHp, qhkHp, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	qSortOrder, qhkSortOrder, _ := qs.GetOK("sortOrder")
	if err := o.bindSortOrder(qSortOrder, qhkSortOrder, route.Formats); err != nil {
		res = append(res, err)
	}

	qSpecial, qhkSpecial, _ := qs.GetOK("special")
	if err := o.bindSpecial(qSpecial, qhkSpecial, route.Formats); err != nil {
		res = append(res, err)
	}

	qSpeed, qhkSpeed, _ := qs.GetOK("speed")
	if err := o.bindSpeed(qSpeed, qhkSpeed, route.Formats); err != nil {
		res = append(res, err)
	}

	qType, qhkType, _ := qs.GetOK("type")
	if err := o.bindType(qType, qhkType, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCollectionPokemonParams) Validate(formats strfmt.Registry) error {
	var res []error

	// attack
	// Required: false
	// AllowEmptyValue: false

	// defense
	// Required: false
	// AllowEmptyValue: false

	// hp
	// Required: false
	// AllowEmptyValue: false

	// limit
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	// name
	// Required: false
	// AllowEmptyValue: false

	// offset
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateOffset(formats); err != nil {
		res = append(res, err)
	}

	// sortOrder
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateSortOrder(formats); err != nil {
		res = append(res, err)
	}

	// special
	// Required: false
	// AllowEmptyValue: false

	// speed
	// Required: false
	// AllowEmptyValue: false

	// type
	// Required: false
	// AllowEmptyValue: false

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAttack binds and validates parameter Attack from query.
func (o *GetCollectionPokemonParams) bindAttack(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("attack", "query", "int64", raw)
	}
	o.Attack = &value

	return nil
}

// bindDefense binds and validates parameter Defense from query.
func (o *GetCollectionPokemonParams) bindDefense(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("defense", "query", "int64", raw)
	}
	o.Defense = &value

	return nil
}

// bindHp binds and validates parameter Hp from query.
func (o *GetCollectionPokemonParams) bindHp(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("hp", "query", "int64", raw)
	}
	o.Hp = &value

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetCollectionPokemonParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetCollectionPokemonParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	if err := o.validateLimit(formats); err != nil {
		return err
	}

	return nil
}

// validateLimit carries on validations for parameter Limit
func (o *GetCollectionPokemonParams) validateLimit(formats strfmt.Registry) error {

	// Required: false
	if o.Limit == nil {
		return nil
	}

	if err := validate.MaximumInt("limit", "query", *o.Limit, 20, false); err != nil {
		return err
	}

	return nil
}

// bindName binds and validates parameter Name from query.
func (o *GetCollectionPokemonParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Name = &raw

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetCollectionPokemonParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetCollectionPokemonParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "int64", raw)
	}
	o.Offset = &value

	if err := o.validateOffset(formats); err != nil {
		return err
	}

	return nil
}

// validateOffset carries on validations for parameter Offset
func (o *GetCollectionPokemonParams) validateOffset(formats strfmt.Registry) error {

	// Required: false
	if o.Offset == nil {
		return nil
	}

	if err := validate.MinimumInt("offset", "query", *o.Offset, 0, false); err != nil {
		return err
	}

	return nil
}

// bindSortOrder binds and validates parameter SortOrder from query.
func (o *GetCollectionPokemonParams) bindSortOrder(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.SortOrder = &raw

	if err := o.validateSortOrder(formats); err != nil {
		return err
	}

	return nil
}

// validateSortOrder carries on validations for parameter SortOrder
func (o *GetCollectionPokemonParams) validateSortOrder(formats strfmt.Registry) error {

	// Required: false
	if o.SortOrder == nil {
		return nil
	}

	if err := validate.EnumCase("sortOrder", "query", *o.SortOrder, []interface{}{"asc", "desc"}, true); err != nil {
		return err
	}

	return nil
}

// bindSpecial binds and validates parameter Special from query.
func (o *GetCollectionPokemonParams) bindSpecial(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("special", "query", "int64", raw)
	}
	o.Special = &value

	return nil
}

// bindSpeed binds and validates parameter Speed from query.
func (o *GetCollectionPokemonParams) bindSpeed(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("speed", "query", "int64", raw)
	}
	o.Speed = &value

	return nil
}

// bindType binds and validates parameter Type from query.
func (o *GetCollectionPokemonParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Type = &raw

	return nil
}
