// Code generated by go-swagger; DO NOT EDIT.

package collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewSearchPokemonParams creates a new SearchPokemonParams object
// with the default values initialized.
func NewSearchPokemonParams() SearchPokemonParams {

	var (
		// initialize parameters with default values

		limitDefault = int64(10)
	)

	return SearchPokemonParams{
		Limit: &limitDefault,
	}
}

// SearchPokemonParams contains all the bound params for the search pokemon operation
// typically these are obtained from a http.Request
//
// swagger:parameters searchPokemon
type SearchPokemonParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Pokémon generation to search for
	  In: query
	*/
	Generation *int64 `query:"generation"`
	/*whether to search for legendary Pokémon
	  In: query
	*/
	Legendary *bool `query:"legendary"`
	/*number of Pokémon to return per page
	  Maximum: 20
	  In: query
	  Default: 10
	*/
	Limit *int64 `query:"limit"`
	/*Pokémon name to search for
	  In: query
	*/
	Name *string `query:"name"`
	/*Pokémon type to search for
	  In: query
	*/
	Type *string `query:"type"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSearchPokemonParams() beforehand.
func (o *SearchPokemonParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qGeneration, qhkGeneration, _ := qs.GetOK("generation")
	if err := o.bindGeneration(qGeneration, qhkGeneration, route.Formats); err != nil {
		res = append(res, err)
	}

	qLegendary, qhkLegendary, _ := qs.GetOK("legendary")
	if err := o.bindLegendary(qLegendary, qhkLegendary, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	qType, qhkType, _ := qs.GetOK("type")
	if err := o.bindType(qType, qhkType, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SearchPokemonParams) Validate(formats strfmt.Registry) error {
	var res []error

	// generation
	// Required: false
	// AllowEmptyValue: false

	// legendary
	// Required: false
	// AllowEmptyValue: false

	// limit
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	// name
	// Required: false
	// AllowEmptyValue: false

	// type
	// Required: false
	// AllowEmptyValue: false

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGeneration binds and validates parameter Generation from query.
func (o *SearchPokemonParams) bindGeneration(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("generation", "query", "int64", raw)
	}
	o.Generation = &value

	return nil
}

// bindLegendary binds and validates parameter Legendary from query.
func (o *SearchPokemonParams) bindLegendary(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("legendary", "query", "bool", raw)
	}
	o.Legendary = &value

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *SearchPokemonParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSearchPokemonParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	if err := o.validateLimit(formats); err != nil {
		return err
	}

	return nil
}

// validateLimit carries on validations for parameter Limit
func (o *SearchPokemonParams) validateLimit(formats strfmt.Registry) error {

	// Required: false
	if o.Limit == nil {
		return nil
	}

	if err := validate.MaximumInt("limit", "query", *o.Limit, 20, false); err != nil {
		return err
	}

	return nil
}

// bindName binds and validates parameter Name from query.
func (o *SearchPokemonParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Name = &raw

	return nil
}

// bindType binds and validates parameter Type from query.
func (o *SearchPokemonParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Type = &raw

	return nil
}
