swagger: "2.0"
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths: {}
definitions:
  Collection:
    type: object
    required:
      - pokemon
    properties:
      name_or_nickname:
        type: string
        description: name or nickname of pokemon
        example: Bulby
      caught:
        type: string
        format: date
        description: date when pokemon was caught
        example: "2024-03-30"
      pokemon:
        $ref: './pokemon.yml#/definitions/Pokemon'
  CollectionPokemon:
    type: object
    required:
      - pokemon_id
      - name_or_nickname
      - type1
      - hp
      - attack
      - defense
      - speed
      - special
      - png
      - description
    properties:
      pokemon_id:
        type: string
        format: uuid4
        description: ID of pokemon
        example: ded12a71-9fc3-430f-8259-a6779f1a7f0c
      name_or_nickname:
        type: string
        description: name or nickname of pokemon
        example: Bulby
      type1:
        type: string
        description: first type of pokemon
        example: Grass
      type2:
        type: string
        description: second type of pokemon
        example: Poison
      hp:
        type: integer
        description: hp of pokemon
        example: 45
      attack:
        type: integer
        description: attack of pokemon
        example: 49
      defense:
        type: integer
        description: defense of pokemon
        example: 49
      speed:
        type: integer
        description: speed of pokemon
        example: 45
      special:
        type: integer
        description: special stat of pokemon
        example: 65
      png:
        type: string
        description: png URL of pokemon
        example: https://play.pokemonshowdown.com/sprites/bw/bulbasaur.png
      description:
        type: string
        description: description of pokemon
        example: A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.
  CollectionPokemonDetail:
    type: object
    required:
      - pokemon_id
      - name_or_nickname
      - caught
      - type1
      - hp
      - attack
      - defense
      - speed
      - special
      - png
      - gif
      - description
    properties:
      pokemon_id:
        type: string
        format: uuid4
        description: ID of pokemon
        example: ded12a71-9fc3-430f-8259-a6779f1a7f0c
      name_or_nickname:
        type: string
        description: name or nickname of pokemon
        example: Bulby
      caught:
        type: string
        format: date
        description: date when pokemon was caught
        example: "2024-03-30"      
      type1:
        type: string
        description: first type of pokemon
        example: Grass
      type2:
        type: string
        description: second type of pokemon
        example: Poison
      hp:
        type: integer
        description: hp of pokemon
        example: 45
      attack:
        type: integer
        description: attack of pokemon
        example: 49
      defense:
        type: integer
        description: defense of pokemon
        example: 49
      speed:
        type: integer
        description: speed of pokemon
        example: 45
      special:
        type: integer
        description: special stat of pokemon
        example: 65
      png:
        type: string
        description: png URL of pokemon
        example: https://play.pokemonshowdown.com/sprites/bw/bulbasaur.png
      gif:
        type: string
        description: gif URL of pokemon
        example: https://play.pokemonshowdown.com/sprites/bwani/bulbasaur.gif
      description:
        type: string
        description: description of pokemon
        example: A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.
  GetCollectionPokemonResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/CollectionPokemon"
      pagination:
        $ref: "./pokemon.yml#/definitions/Pagination"
  GetCollectionPokemonDetailResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/CollectionPokemonDetail"
  PokemonBody:
    type: object
    properties:
      nickname:
        type: string
        description: name or nickname of pokemon
        example: Bulby
      caught:
        type: string
        format: date
        description: date when pokemon was caught
        example: "2024-03-30"
