swagger: "2.0"
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths: {}
definitions:
  Collection:
    type: object
    required:
      - Pokemon
    properties:
      Pokemon:
        $ref: './pokemon.yml#/definitions/Pokemon'
