swagger: "2.0"
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths: {}
definitions:
  Pokemon:
    type: object
    required:
      - pokemon_id
      - name
      - type_1
      - generation
      - legendary
    properties:
      pokemon_id:
        type: string
        format: uuid4
        description: ID of pokemon
        example: 891d37d3-c74f-493e-aea8-af73efd92016
      name:
        type: string
        description: name of pokemon
        example: pikachu
      type_1:
        type: string
        description: first type of pokemon
        example: electric
      type_2:
        type: string
        description: second type of pokemon
        example: flying
      generation:
        type: integer
        description: generation of pokemon
        example: 1
      legendary:
        type: boolean
        description: is the pokemon legendary?
        example: false
