swagger: "2.0"
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths: {}
definitions:
  Pokemon:
    type: object
    required:
      - pokemon_id
      - name
      - type1
    properties:
      pokemon_id:
        type: string
        format: uuid4
        description: ID of the pokemon
        example: 891d37d3-c74f-493e-aea8-af73efd92016
      name:
        type: string
        description: name of the pokemon
        example: Pikachu
      type1:
        type: string
        description: first type of the pokemon
        example: Electric
      type2:
        type: string
        description: second type of the pokemon
        example: Flying
      generation:
        type: integer
        description: generation of the pokemon
        example: 1
      legendary:
        type: boolean
        description:  is the pokemon legendary?
        example: false
  Pagination:
    type: object
    properties:
      total:
        type: integer
        description: total number of pokemon matching the query
      limit:
        type: integer
        description: number of pokemon returned per page
      offset:
        type: integer
        description: number of pokemon skipped before returning results
  GetPokemonResponse:
    type: object
    required:
      - data
      - pagination
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/Pokemon"
        description: list of pokemon objects
      pagination:
        $ref: "#/definitions/Pagination"
  GetDownloadResponse:
      type: object
      required:
        - message
        - status
      properties:
        message:
          type: string
          description: Result message of the download operation
          example: "CSV download successful"
        status:
          type: integer
          description: HTTP status code of the operation
          example: 200
