swagger: "2.0"
info:
  title: github.com/ansiegl/Pok-Nest.git
  version: 0.1.0
paths: {}
definitions:
  Pokemon:
    type: object
    required:
      - pokemon_id
      - name
      - type_1
      - generation
      - legendary
    properties:
      pokemon_id:
        type: string
        format: uuid4
        description: ID of pokemon
        example: ee51afeb-b86c-444d-a0db-746e7a53139c
      name:
        type: string
        description: name of pokemon
        example: Bulbasaur
      type_1:
        type: string
        description: first type of pokemon
        example: Grass
      type_2:
        type: string
        description: second type of pokemon
        example: Poison
      generation:
        type: integer
        description: generation of pokemon
        example: 1
      legendary:
        type: boolean
        description: is the pokemon legendary?
        example: false
